// src/components/cards/UltraFavoriteCard.svelte
<script lang="ts">
	import { Badge, Button, ButtonGroup, Card, Tooltip } from "flowbite-svelte";
	import Icon from "@iconify/svelte";
  import type { Favorite } from "@/models";
	const { favorite }: { favorite: Favorite} = $props();
</script>

<div
	class="relative rounded-xl h-[260px] w-42 max-w-42 flex flex-col p-1  items-center transition-transform duration-300 ease-in-out border border-transparent outline-none bg-gray-900 hover:bg-gray-800 hover:cursor-pointer hover:shadow-lg hover:z-30 transform hover:scale-[1.08] hover:border-white hover:border-1 focus:bg-gray-800 focus:shadow-lg focus:scale-[1.08] focus:border-white focus:border-1"
>
	<img src={favorite.cover} alt={favorite.name} class="w-40 h-60 min-w-40 max-w-40 min-h-60 max-h-60 mt-3 mb-2 object-contain rounded-b-xl bg-gray-500" />
		<div class="w-full h-full fixed flex flex-col justify-between items-center ">

		<Badge class="w-40 rounded-xl" color="dark"> {favorite.name.length > 16 ? favorite.name.substring(0, 16) + "..." : favorite.name}</Badge>
		<div class="w-full h-10 flex justify-center pb-1 ">
			<!-- <ButtonGroup>
				<Button color="dark" size="sm">
					<Icon icon="lucide:book-open-text" class="w-4 h-4" />
				</Button>
				<Button color="dark" size="sm">
					<Icon icon="lucide:square-pen" class="w-4 h-4" />
				</Button>
				<Button color="dark" size="sm">
					<Icon icon="lucide:circle-x" class="w-4 h-4" />
				</Button>
			</ButtonGroup> -->
		</div>
	</div>
</div>

// src/components/UltraFavoriteCard.vue
<script setup lang="ts">
import { ReadedDB } from '~/database';
import { isReaded } from '~/functions';
import type { DownloadManager } from '~/managers/downloadManager';
import type { Favorite } from '~/models';
const { favorite } = defineProps<{
  favorite: Favorite;
}>();
const dlManager = useState<DownloadManager>('dlManager');
const isFavoriteOpen = useState<boolean>('isFavoriteOpen');
const favoriteOpen = useState<Favorite>('favorite');
const isLoading = ref(false);
const chaptersToRead = ref();
const chaptersReaded = ref();
onMounted(async () => {
  isLoading.value = true;
  const readeds = await ReadedDB.getReadeds(favorite);
  const chapters = await dlManager.value.getChapters(favorite);
  isLoading.value = false;
  if (!chapters.ok) {
    chaptersToRead.value = 'Error';
    chaptersReaded.value = 'Error';
    return;
  }
  const chaptersLen = Number(chapters?.chapters?.length) ?? 0;
  let countToRead = 0;
  //@ts-ignore
  for (const chapter of chapters.chapters) {
    if (isReaded(chapter, readeds)) {
      break;
    }
    countToRead++;
  }
  //@ts-ignore
  chaptersToRead.value =
    countToRead > 0
      //@ts-ignore
      ? `+${countToRead}`
      : 'All readed';
  //@ts-ignore
  chaptersReaded.value = `${chaptersLen - countToRead}/${chapters.chapters.length}`;
});
function openFavorite() {
  favoriteOpen.value = favorite;
  isFavoriteOpen.value = true;
}
</script>

<template>
  <div>
    <div class="relative bg-gray-900 rounded-xl h-[280px] w-40 flex flex-col !p-0 items-center hover:bg-gray-800 hover:cursor-pointer hover:shadow-lg transition-transform duration-300 ease-in-out transform hover:scale-[1.08] hover:z-10 border border-transparent hover:border-white hover:border-2" @click="openFavorite">
    <UTooltip :prevent="favorite.name.length < 17" :text=favorite.name :popper="{ placement: 'bottom', arrow: true }" >
      <UBadge class="w-36 m-1 flex justify-center cursor-default" color="white" variant="solid" >
        {{ favorite.name.substring(0, 16) + (favorite.name.length > 16? "..." : "") }}
      </UBadge>
    </UTooltip>
    <NuxtImg :src="favorite.cover" class="h-52 w-36 object-contain rounded-xl select-none" />
    <UButtonGroup orientation="horizontal" class="w-full flex justify-center">
      <UButton
        @click="openFavorite"
        class="h-8"
        color="white"
        variant="solid"
        icon="i-heroicons-book-open-solid"
      />
      <UTooltip :prevent="isLoading" :text="chaptersReaded" :popper="{ placement: 'top', arrow: true,  }" >
        <UButton
          class="cursor-default disabled:cursor-default"
          :loading="isLoading"
          color="white"
          variant="solid"
        >
          {{ chaptersToRead }}
        </UButton>
      </UTooltip>
    </UButtonGroup>
  </div>
  </div>
</template>
