// src/pages/reader/[favoriteId]/[chapterIndex].vue
<script setup lang="ts">
  import { getCurrentWindow } from "@tauri-apps/api/window";
  import { invoke } from "@tauri-apps/api/core";
  import { FavoriteRepository, ReadedRepository } from "~/repositories";
  import { addReadedBelow } from "~/functions";
  import { DownloadManager } from "~/managers";
  import { Chapter } from "~/models";

  const route = useRoute();
  const { favoriteId, chapterIndex } = route.params;
  const mode = (route.query.mode as string) || "internal";
  const key = (route.query.key as string) || "";

  let data = undefined;
  if (mode === "external") {
    data = await invoke("get_data", { key: key });
    console.log(data);
  }
  const toast = useToast();
  const window = getCurrentWindow();
  const dlManager = useState<DownloadManager>(
    "dlManager",
    () => new DownloadManager()
  );
  const pages = ref<string[]>([]);
  const favorite = await FavoriteRepository.getFavorite(favoriteId);
  //@ts-ignore
  const chapters = useState<Chapter[]>("chapters", () => data.chapters);
  const chapter = ref<Chapter>(chapters.value[Number(chapterIndex)]);
  const currentlyCount = useState<number>("currentlyCount", () => 1);
  const totalPage = useState<number>("totalPage");
  const currentlyPage = useState<string>("currentlyPage", () => "/myk.png");
  const openMenuChapters = ref(false);
  const isTheLastChapter = ref(chapter.value === chapters.value[0]);
  const zoom = ref(0);
  const zoomMinusDown = ref(false);
  const zoomPlusDown = ref(false);
  window.setTitle(`MangaYouKnow - ${favorite.name} / ${chapter.value.number}`);
  function toNextPage() {
    if (currentlyCount.value === totalPage.value) return;
    currentlyCount.value++;
    currentlyPage.value = pages.value[currentlyCount.value - 1];
  }
  function toPrevPage() {
    if (currentlyCount.value === 1) return;
    currentlyCount.value--;
    currentlyPage.value = pages.value[currentlyCount.value - 1];
  }
  async function readNextOrPrevChapter(way: "next" | "prev" = "next") {
    const nextChapter =
      chapters.value[
        chapters.value.indexOf(chapter.value) - (way === "next" ? 1 : -1)
      ];
    await navigateTo(
      `/reader/${favoriteId}/${chapters.value.indexOf(nextChapter)}`
    );
    closeMenu();
  }
  async function fetchPages() {
    useHead({
      title: favorite.name,
      link: pages.value.map((image) => {
        return {
          rel: "preload",
          href: image,
          as: "image",
        };
      }),
    });
  }
  function closeMenu() {
    openMenuChapters.value = false;
  }
  defineShortcuts(
    {
      f4: {
        usingInput: true,
        handler: () => {
          if (mode !== "external") navigateTo(useRoute().redirectedFrom);
        },
      },
      arrowleft: {
        usingInput: true,
        handler: toPrevPage,
      },
      arrowright: {
        usingInput: true,
        handler: toNextPage,
      },
      "ctrl_=": {
        usingInput: true,
        handler: () => {
          zoom.value += 1;
        },
      },
      "ctrl_-": {
        usingInput: true,
        handler: () => {
          zoom.value -= 1;
        },
      },
    },
    { chainDelay: 400 }
  );
  onMounted(async () => {
    toast.add({
      title: `Chapter ${chapter.value.number}`,
      description: favorite.name,
      color: "info",
      icon: "i-lucide-book-a",
      duration: 1000,
      click: () => {
        toast.clear();
      },
    });
    pages.value = await dlManager.value.getChapterImages(chapter.value);
    await addReadedBelow(
      chapter.value,
      chapters.value,
      favorite,
      undefined,
      true
    );
    totalPage.value = pages.value.length;
    currentlyPage.value = pages.value[0];
    currentlyCount.value = 1;
    isTheLastChapter.value = chapter.value === chapters.value[0];
    fetchPages();
  });
  watch(zoomMinusDown, async () => {
    zoom.value -= 1;
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve(true);
      }, 500);
    });
    while (zoomMinusDown.value) {
      await new Promise((resolve) => {
        setTimeout(() => {
          resolve(true);
        }, 100);
      });
      zoom.value -= 1;
    }
  });
  watch(zoomPlusDown, async () => {
    zoom.value += 1;
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve(true);
      }, 500);
    });
    while (zoomPlusDown.value) {
      await new Promise((resolve) => {
        setTimeout(() => {
          resolve(true);
        }, 100);
      });
      zoom.value += 1;
    }
  });
</script>

<template>
  <!--@vue-ignore-->
  <MenuChaptersSlideover
    v-model:open="openMenuChapters"
    :chapters="chapters"
    :currentlyChapter="chapter"
    :readChapterNextOrPrev="readNextOrPrevChapter"
    :closeMenu="closeMenu"
    :mode="mode"
  />
  <div
    class="fixed w-screen h-screen z-50 pointer-events-none flex justify-end items-center"
  >
    <UButton
      size="xl"
      v-if="currentlyCount === totalPage && !isTheLastChapter"
      icon="heroicons:arrow-right-solid"
      color="neutral"
      class="pointer-events-auto"
      @click="() => readNextOrPrevChapter('next')"
    />
  </div>
  <div class="fixed w-screen h-screen flex">
    <button
      class="w-[50%] cursor-default outline-none border-none"
      tabindex="-1"
      @click="toPrevPage"
    />
    <button
      class="w-[50%] cursor-default outline-none border-none"
      tabindex="-1"
      @click="toNextPage"
    />
  </div>
  <div
    class="fixed w-screen gap-1 p-[1%] flex flex-col justify-end items-end pointer-events-none"
  >
    <div class="flex gap-1 z-30">
      <UBadge class="m-1" color="neutral" variant="outline">
        {{ currentlyCount }} / {{ totalPage }}
      </UBadge>
      <UButton
        size="xl"
        class="pointer-events-auto"
        icon="i-lucide-menu"
        color="neutral"
        variant="outline"
        @click="openMenuChapters = true"
      />
      <UPopover mode="hover" arrow>
        <UButton
          class="pointer-events-auto"
          size="xl"
          icon="nimbus:arrows-horizontal"
          color="neutral"
          variant="outline"
        />
        <template #content>
          <div class="p-2 gap-1 flex flex-row rounded-lg">
            <UButton
              size="xl"
              icon="i-lucide-arrow-left"
              color="neutral"
              variant="outline"
              :disabled="
                chapter.number === chapters[chapters.length - 1].number
              "
              @click="readNextOrPrevChapter('prev')"
            />
            <UButton
              size="xl"
              icon="i-lucide-arrow-right"
              color="neutral"
              variant="outline"
              :disabled="isTheLastChapter"
              @click="readNextOrPrevChapter('next')"
            />
          </div>
        </template>
      </UPopover>
    </div>
    <div class="flex gap-2">
      <UButtonGroup class="gap-0.5 pointer-events-auto z-50">
        <UButton
          color="neutral"
          variant="outline"
          icon="ic:round-minus"
          @mousedown="zoomMinusDown = true"
          @mouseup="zoomMinusDown = false"
        />
        <UButton
          class="w-10 p-0 flex justify-center"
          color="neutral"
          variant="outline"
          @click="zoom = 0"
          :label="zoom * 2 + 100 + '%'"
        />
        <UButton
          color="neutral"
          variant="outline"
          icon="ic:round-plus"
          @mousedown="zoomPlusDown = true"
          @mouseup="zoomPlusDown = false"
        />
      </UButtonGroup>
      <UButton
        class="pointer-events-auto z-50"
        icon="ic:outline-fullscreen-exit"
        color="neutral"
        variant="outline"
        @click="
          async () => {
            window.setFullscreen(!(await window.isFullscreen()));
          }
        "
      />
    </div>
    <div flex="flex gap-1 z-30">
      <UTooltip :text="`${favorite.name} / ${chapter.number}`">
        <UButtonGroup class="pointer-events-auto">
          <UBadge
            class="w-[5.5rem] rounded-r-none"
            color="neutral"
            variant="outline"
            :label="favorite.name"
          />
          <UBadge
            class="w-10 rounded-l-none flex justify-center items-center px-2"
            color="neutral"
            variant="outline"
            :label="chapter.number.toString()"
          />
        </UButtonGroup>
      </UTooltip>
    </div>
  </div>

  <div class="h-full w-full overflow-auto">
    <div class="min-h-full w-full flex items-center justify-center">
      <NuxtImg
        :src="currentlyPage"
        placeholder
        class="object-contain transition-all duration-200"
        :style="{
          height: `calc(100vh + ${zoom}rem)`,
          maxWidth: '100%',
          maxHeight: `calc(100vh + ${zoom}rem)`,
        }"
      />
    </div>
  </div>
</template>

// src/routes/reader/[favoriteId]/[chapterIndex]/+page.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { shortcuts } from "svelte-keyboard-shortcuts";
  import { getCurrentWindow } from "@tauri-apps/api/window";
  import { invoke } from "@tauri-apps/api/core";
  import { FavoriteRepository, ReadedRepository } from "@/repositories";
  import { addReadedBelow } from "@/functions";
  import { Chapter, Favorite } from "@/models";
  import { Button, Badge, HoverCard, Tooltip } from "@/lib/components";
  import { downloadManager, chapters, readeds } from "@/store";
  import Icon from "@iconify/svelte";
  import { goto, onNavigate, afterNavigate } from "$app/navigation";
  import { onMount } from "svelte";

  let { favoriteId, chapterIndex } = page.params;
  let chapter = $state($chapters[Number(chapterIndex)]);
  let favorite: Favorite | null = $state(null);
  let images: string[] = $state([]);
  let currentlyCount = $state(1);
  let totalPage = $state(0);
  let isTheLastChapter = $state(Number(chapterIndex) === 0);
  let isTheFirstChapter = $state(Number(chapterIndex) === $chapters.length - 1);
  let currentlyImage = $state("/myk.png");
  const currentWindow = getCurrentWindow();
  onMount(async () => {
    currentWindow.setFullscreen(true);
    favorite = await FavoriteRepository.getFavorite(Number(favoriteId));
    const chapterImages = await $downloadManager.getChapterImages(chapter);
    images = chapterImages;
    currentlyImage = images[0];
    totalPage = images.length;
    await addReadedBelow(chapter, $chapters, favorite, $readeds, true);
    const newReadeds = await ReadedRepository.getReadeds(favorite);
    readeds.set(newReadeds);
  });

  afterNavigate(async () => {
    favoriteId = page.params.favoriteId;
    chapterIndex = page.params.chapterIndex;
    isTheFirstChapter = Number(chapterIndex) === $chapters.length - 1;
    isTheLastChapter = Number(chapterIndex) === 0;
    chapter = $chapters[Number(chapterIndex)];
    const chaptersImages = await $downloadManager.getChapterImages(chapter);
    images = chaptersImages;
    currentlyImage = chaptersImages[0];
    totalPage = chaptersImages.length;
    favorite = await FavoriteRepository.getFavorite(Number(favoriteId));
    await addReadedBelow(chapter, $chapters, favorite, $readeds, true);
    const newReadeds = await ReadedRepository.getReadeds(favorite);
    readeds.set(newReadeds);
  });
  function prevPage() {
    if (currentlyCount === 1) return;
    currentlyCount--;
    currentlyImage = images[currentlyCount - 1];
  }
  function nextPage() {
    if (currentlyCount === totalPage) return;
    currentlyCount++;
    currentlyImage = images[currentlyCount - 1];
  }
  async function handleGoChapter(way: "next" | "prev") {
    currentlyImage = "/myk.png";
    currentlyCount = 1;
    totalPage = 1;
    if (way === "next") {
      console.log(Number(chapterIndex) - 1);
      await goto(`/reader/${favoriteId}/${Number(chapterIndex) - 1}`);
    } else {
      console.log(Number(chapterIndex) + 1);
      await goto(`/reader/${favoriteId}/${Number(chapterIndex) + 1}`);
    }
  }
</script>

<div
  class="fixed w-screen h-screen z-50 pointer-events-none flex justify-end items-center"
>
  {#if currentlyCount === totalPage && !isTheLastChapter}
    <Button class="pointer-events-auto" onclick={() => handleGoChapter("next")}>
      <Icon icon="lucide:arrow-right" /></Button
    >
  {/if}
</div>
<div class="fixed w-screen h-screen flex">
  <button
    aria-label="Previous"
    class="w-[50%] cursor-default outline-none border-none"
    tabindex="-1"
    onclick={prevPage}
    use:shortcuts={{ keys: ["ArrowLeft"] }}
  ></button>
  <button
    aria-label="Next"
    class="w-[50%] cursor-default outline-none border-none"
    tabindex="-1"
    onclick={nextPage}
    use:shortcuts={{ keys: ["ArrowRight"] }}
  ></button>
</div>
<div
  class="fixed w-screen gap-1 p-[1%] flex flex-col justify-end items-end pointer-events-none"
>
  <div class="flex gap-1 z-30">
    <Badge class="rounded-md m-1" color="neutral" variant="outline"
      >{currentlyCount} / {totalPage}
    </Badge>
    <Button
      class="pointer-events-auto"
      size="sm"
      color="neutral"
      variant="outline"
      onclick={async () => {
        goto("/home");
        currentWindow.setFullscreen(false);
      }}><Icon icon="lucide:home" /></Button
    >
    <HoverCard.Root openDelay={50} closeDelay={100}>
      <HoverCard.Trigger>
        <Button
          class="pointer-events-auto"
          size="sm"
          color="neutral"
          variant="outline"
          ><Icon icon="nimbus:arrows-horizontal" />
        </Button>
      </HoverCard.Trigger>
      <HoverCard.Content
        class="w-24 h-12 !p-1 flex flex-row gap-0.5"
        sideOffset={-5}
      >
        <Button
          disabled={isTheFirstChapter}
          size="sm"
          variant="outline"
          effect="gooeyLeft"
          onclick={() => handleGoChapter("prev")}
          ><Icon icon="lucide:arrow-left" /></Button
        >
        <Button
          disabled={isTheLastChapter}
          size="sm"
          variant="outline"
          effect="gooeyRight"
          onclick={() => handleGoChapter("next")}
          ><Icon icon="lucide:arrow-right" /></Button
        >
      </HoverCard.Content>
    </HoverCard.Root>
  </div>
  <div class="flex gap-2">
    <div class="inline-flex pointer-events-auto z-50">
      <Button class="w-6 rounded-r-none" size="sm" variant="outline"
        ><Icon icon="lucide:minus" /></Button
      >
      <Button
        class="w-8 p-0 flex justify-center rounded-none"
        size="sm"
        variant="outline">100%</Button
      >
      <Button class="w-6 rounded-l-none" size="sm" variant="outline"
        ><Icon icon="lucide:plus" /></Button
      >
    </div>
    <Button
      class="pointer-events-auto z-50"
      size="sm"
      variant="outline"
      onclick={async () => {
        currentWindow.setFullscreen(!(await currentWindow.isFullscreen()));
      }}
    >
      <Icon icon="lucide:maximize" />
    </Button>
  </div>
  <div class="flex gap-1 z-30">
    <Tooltip.Provider>
      <Tooltip.Root>
        <Tooltip.Trigger>
          <div class="w-[135px] inline-flex pointer-events-auto cursor-default">
            <Badge
              class="w-[100px] text-[11px] rounded-r-none"
              color="neutral"
              variant="outline"
            >
              {favorite?.name
                ? favorite.name.length > 11
                  ? favorite.name.substring(0, 11) + "..."
                  : favorite.name
                : ""}
            </Badge>
            <Badge
              class="w-10 rounded-l-none flex justify-center items-center px-2"
              color="neutral"
              variant="outline"
            >
              {chapter.number.toString()}
            </Badge>
          </div>
        </Tooltip.Trigger>
        <Tooltip.Content side="bottom">
          <p>{`${favorite?.name} / ${chapter.number}`}</p>
        </Tooltip.Content>
      </Tooltip.Root>
    </Tooltip.Provider>
  </div>
</div>

<div class="h-full w-full overflow-auto">
  <div class="min-h-full w-full flex items-center justify-center">
    <img
      src={currentlyImage}
      alt="manga"
      class="object-contain h-screen transition-all duration-200"
    />
  </div>
</div>

{#each images as image}
  <img class="hidden" src={image} alt="Prefetched" data-sveltekit-prefetch />
{/each}
